# Generated by Django 3.1.6 on 2023-07-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20230630_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='amount',
            new_name='value',
        ),
    ]
